<?php


//This test generated by ChatGPT for automated testing of the OrdersDao class

require_once __DIR__ . '/rest/dao/OrdersDao.php';
require_once __DIR__ . '/rest/dao/UsersDao.php';

$ordersDao = new OrdersDao();
$testUser = [
    "userID" => "U001",
    "username" => "testuser",
    "email" => "testuser@example.com",
    "password" => "password123",
    "firstName" => "Test",
    "lastName" => "User",
    "dateJoined" => "2025-04-01",
    "address" => "123 Test St, Test City, TC"
];

$userDao = new UsersDao();
$userDao->insert_user($testUser);
// Test order data
$testOrder = [
    "orderID" => "O001",
    "userID" => "U001",
    "orderDate" => "2025-04-01",
    "shippingAddress" => "123 Test St, Test City, TC",
    "totalPrice" => 59.99,
    "orderStatus" => "Pending"
];

// Insert a new order
$insertResult = $ordersDao->insert_order($testOrder);
echo "Insert:\n";
print_r($insertResult);

// Get all orders
$allOrders = $ordersDao->get_all_orders();
echo "\nAll Orders:\n";
print_r($allOrders);

// Get a specific order by ID
$singleOrder = $ordersDao->get_order_by_id("O001");
echo "\nSingle Order by ID:\n";
print_r($singleOrder);

// Get orders by userID
$userOrders = $ordersDao->get_orders_by_user("U001");
echo "\nOrders by User ID:\n";
print_r($userOrders);

// Update order information
$testOrderUpdate = [
    "orderID" => "O001",
    "userID" => "U001",
    "orderDate" => "2025-04-02",  // Updated order date
    "shippingAddress" => "456 Updated St, Updated City, UC",
    "totalPrice" => 99.99,  // Updated total price
    "orderStatus" => "Shipped"  // Updated order status
];

$updateResult = $ordersDao->update_order($testOrderUpdate);
echo "\nUpdate:\n";
print_r($updateResult);

// Delete order
$deleteResult = $ordersDao->delete_order("O001");
echo "\nDelete:\n";
print_r($deleteResult);
